package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"os"
	"time"

	"github.com/urfave/cli/v2"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/consensus"
	"github.com/ethereum/go-ethereum/consensus/beacon"
	"github.com/ethereum/go-ethereum/consensus/misc"
	"github.com/ethereum/go-ethereum/consensus/misc/eip4844"
	"github.com/ethereum/go-ethereum/core"
	gstate "github.com/ethereum/go-ethereum/core/state"
	"github.com/ethereum/go-ethereum/core/stateless"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/core/vm"
	logger2 "github.com/ethereum/go-ethereum/eth/tracers/logger"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/params"
	"github.com/ethereum/go-ethereum/rpc"
	"github.com/ethereum/go-ethereum/triedb"

	op_service "github.com/ethereum-optimism/optimism/op-service"
	"github.com/ethereum-optimism/optimism/op-service/cliapp"
	"github.com/ethereum-optimism/optimism/op-service/ctxinterrupt"
	oplog "github.com/ethereum-optimism/optimism/op-service/log"
	"github.com/ethereum-optimism/optimism/op-service/retry"
)

// =============================================================================
// CLI Flags and Configuration
// =============================================================================

var EnvPrefix = "OP_REPLAY_SEQ"

var (
	RPCFlag = &cli.StringFlag{
		Name:     "rpc",
		Usage:    "RPC endpoint to fetch data from",
		EnvVars:  op_service.PrefixEnvVar(EnvPrefix, "RPC"),
		Required: true,
	}
	StartFlag = &cli.IntFlag{
		Name:     "start",
		Usage:    "Start block number",
		EnvVars:  op_service.PrefixEnvVar(EnvPrefix, "START"),
		Required: true,
	}
	EndFlag = &cli.IntFlag{
		Name:     "end",
		Usage:    "End block number",
		EnvVars:  op_service.PrefixEnvVar(EnvPrefix, "END"),
		Required: true,
	}
	OutPathFlag = &cli.PathFlag{
		Name:    "out",
		Usage:   "Path to directory to write trace data files (optional, if not specified no files will be written)",
		EnvVars: op_service.PrefixEnvVar(EnvPrefix, "OUT"),
		Value:   "",
	}
)

// =============================================================================
// Core Data Structures (mimicking miner structures)
// =============================================================================

// generateParams wraps various settings for generating sealing task.
// This structure mirrors the miner's generateParams exactly.
type generateParams struct {
	timestamp   uint64            // The timestamp for sealing task
	forceTime   bool              // Flag whether the given timestamp is immutable or not
	parentHash  common.Hash       // Parent block hash, empty means the latest chain head
	coinbase    common.Address    // The fee recipient address for including transaction
	random      common.Hash       // The randomness generated by beacon chain, empty before the merge
	withdrawals types.Withdrawals // List of withdrawals to include in block (shanghai field)
	beaconRoot  *common.Hash      // The beacon root (cancun field).
	noTxs       bool              // Flag whether an empty block without any transaction is expected

	txs           types.Transactions // Deposit transactions to include at the start of the block
	gasLimit      *uint64            // Optional gas limit override
	eip1559Params []byte             // Optional EIP-1559 parameters
	interrupt     *int32             // Optional interruption signal to pass down to worker.generateWork
	isUpdate      bool               // Optional flag indicating that this is building a discardable update

	rpcCtx context.Context // context to control block-building RPC work. No RPC allowed if nil.
}

// environment contains all the information needed for block generation.
// This structure mirrors the miner's environment exactly.
type environment struct {
	signer   types.Signer
	state    *gstate.StateDB // apply state changes here
	tcount   int             // tx count in cycle
	gasPool  *core.GasPool   // available gas used to pack transactions
	coinbase common.Address
	evm      *vm.EVM

	header   *types.Header
	txs      []*types.Transaction
	receipts []*types.Receipt
	sidecars []*types.BlobTxSidecar
	blobs    int

	witness *stateless.Witness

	noTxs  bool            // true if we are reproducing a block, and do not have to check interop txs
	rpcCtx context.Context // context to control block-building RPC work. No RPC allowed if nil.
}

// newPayloadResult is the result of payload generation.
// This structure mirrors the miner's newPayloadResult exactly.
type newPayloadResult struct {
	err      error
	block    *types.Block
	fees     *big.Int
	sidecars []*types.BlobTxSidecar
	stateDB  *gstate.StateDB
	receipts []*types.Receipt
	requests [][]byte
	witness  *stateless.Witness
}

// ReplayMiner simulates the miner structure for replay purposes.
// This allows us to reuse miner logic while adapting it for replay scenarios.
type ReplayMiner struct {
	chainConfig *params.ChainConfig
	chain       *remoteChainCtx
	logger      log.Logger
}

// remoteChainCtx provides access to block-headers, for usage by the state-transition,
// such as basefee computation (based on prior block) and EVM block-hash opcode.
type remoteChainCtx struct {
	consensusEng consensus.Engine
	hdr          *types.Header
	cfg          *params.ChainConfig
	cl           *ethclient.Client
	logger       log.Logger
	currentState *gstate.StateDB // Added to support state access in replay mode
}

// =============================================================================
// Error Constants
// =============================================================================

var (
	errTxConditionalInvalid = errors.New("transaction conditional invalid")
)

// =============================================================================
// Main Application Entry Point
// =============================================================================

func main() {
	flags := []cli.Flag{
		RPCFlag, StartFlag, EndFlag, OutPathFlag,
	}
	flags = append(flags, oplog.CLIFlags(EnvPrefix)...)

	app := cli.NewApp()
	app.Name = "op-replay-seq"
	app.Usage = "Replay a range of blocks using sequencer logic."
	app.Description = "Replay a range of blocks using sequencer logic and verify state roots."
	app.Flags = cliapp.ProtectFlags(flags)
	app.Action = mainAction
	app.Writer = os.Stdout
	app.ErrWriter = os.Stderr
	err := app.Run(os.Args)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Application failed: %v", err)
		os.Exit(1)
	}
}

func mainAction(c *cli.Context) error {
	ctx := ctxinterrupt.WithCancelOnInterrupt(c.Context)
	logCfg := oplog.ReadCLIConfig(c)
	logger := oplog.NewLogger(c.App.Writer, logCfg)

	rpcEndpoint := c.String(RPCFlag.Name)
	start := c.Int(StartFlag.Name)
	end := c.Int(EndFlag.Name)
	outDir := c.Path(OutPathFlag.Name)

	if start > end {
		return fmt.Errorf("start block (%d) must be less than or equal to end block (%d)", start, end)
	}

	// Create output directory if it doesn't exist
	if outDir != "" {
		if err := os.MkdirAll(outDir, 0755); err != nil {
			return fmt.Errorf("failed to create output directory: %w", err)
		}
	}

	cl, err := rpc.DialContext(ctx, rpcEndpoint)
	if err != nil {
		return fmt.Errorf("failed to dial RPC: %w", err)
	}
	defer cl.Close()

	ethCl := ethclient.NewClient(cl)
	db := NewHybridRemoteDB(cl)

	var config *params.ChainConfig
	if err := cl.CallContext(ctx, &config, "debug_chainConfig"); err != nil {
		return fmt.Errorf("failed to fetch chain config: %w", err)
	}

	// Print chain configuration details
	logger.Info("Chain configuration loaded",
		"chain_id", config.ChainID,
		"homestead_block", config.HomesteadBlock,
		"dao_fork_block", config.DAOForkBlock,
		"dao_fork_support", config.DAOForkSupport,
		"eip150_block", config.EIP150Block,
		"eip155_block", config.EIP155Block,
		"eip158_block", config.EIP158Block,
		"byzantium_block", config.ByzantiumBlock,
		"constantinople_block", config.ConstantinopleBlock,
		"petersburg_block", config.PetersburgBlock,
		"istanbul_block", config.IstanbulBlock,
		"muir_glacier_block", config.MuirGlacierBlock,
		"berlin_block", config.BerlinBlock,
		"london_block", config.LondonBlock,
		"arrow_glacier_block", config.ArrowGlacierBlock,
		"gray_glacier_block", config.GrayGlacierBlock,
		"shanghai_time", config.ShanghaiTime,
		"cancun_time", config.CancunTime,
		"prague_time", config.PragueTime,
		"terminal_total_difficulty", config.TerminalTotalDifficulty,
		"optimism_config", config.Optimism != nil,
		"clique_config", config.Clique != nil,
	)

	// Print detailed Optimism configuration if available
	if config.Optimism != nil {
		logger.Info("Optimism configuration",
			"eip1559_elasticity", config.Optimism.EIP1559Elasticity,
			"eip1559_denominator", config.Optimism.EIP1559Denominator,
			"eip1559_denominator_canyon", config.Optimism.EIP1559DenominatorCanyon,
		)
	}

	// Print detailed Clique configuration if available
	if config.Clique != nil {
		logger.Info("Clique configuration",
			"epoch", config.Clique.Epoch,
			"period", config.Clique.Period,
		)
	}

	// Print additional hardfork timestamps if available
	if config.RegolithTime != nil {
		logger.Info("Regolith hardfork", "time", *config.RegolithTime)
	}
	if config.CanyonTime != nil {
		logger.Info("Canyon hardfork", "time", *config.CanyonTime)
	}
	if config.EcotoneTime != nil {
		logger.Info("Ecotone hardfork", "time", *config.EcotoneTime)
	}
	if config.FjordTime != nil {
		logger.Info("Fjord hardfork", "time", *config.FjordTime)
	}
	if config.InteropTime != nil {
		logger.Info("Interop hardfork", "time", *config.InteropTime)
	}

	logger.Info("Starting block range replay using sequencer logic", "start", start, "end", end)

	// Get parent block of the start block
	parentBlock, err := ethCl.HeaderByNumber(ctx, big.NewInt(int64(start-1)))
	if err != nil {
		return fmt.Errorf("failed to fetch parent block %d: %w", start-1, err)
	}

	stateDB := gstate.NewDatabase(triedb.NewDatabase(db, &triedb.Config{
		Preimages: true,
	}), nil)

	currentState, err := gstate.New(parentBlock.Root, stateDB)
	if err != nil {
		return fmt.Errorf("failed to create initial state from block %d: %w", start-1, err)
	}
	logger.Info("Initialized state from parent block", "parent_number", start-1, "parent_root", parentBlock.Root)

	// Create ReplayMiner and remoteChainCtx once, outside the block processing loop
	// This matches the miner pattern where these objects are created once and reused
	consensusEng := beacon.New(&beacon.OpLegacy{})
	chCtx := &remoteChainCtx{
		consensusEng: consensusEng,
		hdr:          parentBlock, // Will be updated for each block
		cfg:          config,
		cl:           ethCl,
		logger:       logger,
		currentState: currentState, // Will be updated for each block
	}
	replayMiner := NewReplayMiner(config, chCtx, logger)

	// Stats tracking
	var (
		totalBlocks    = 0
		successBlocks  = 0
		mismatchBlocks = 0
		prevBlockHash  common.Hash // Track previous block hash for validation
	)

	// Process each block in the range
	for i := start; i <= end; i++ {
		logger.Info("Processing block", "number", i)

		// Fetch the block
		block, err := ethCl.BlockByNumber(ctx, big.NewInt(int64(i)))
		if err != nil {
			return fmt.Errorf("failed to fetch block %d: %w", i, err)
		}

		// Basic block validation
		if block.NumberU64() != uint64(i) {
			return fmt.Errorf("block number mismatch: expected %d, got %d", i, block.NumberU64())
		}

		// Verify parent block connection (except for the first block)
		if i > start {
			expectedParentHash := prevBlockHash
			if block.ParentHash() != expectedParentHash {
				return fmt.Errorf("parent hash mismatch at block %d: expected %s, got %s",
					i, expectedParentHash, block.ParentHash())
			}
		}

		// Create output file for this block's trace
		var outW io.Writer = io.Discard // Default to discard if no output directory
		if outDir != "" {
			outPath := fmt.Sprintf("%s/block_%d_trace.txt", outDir, i)
			file, err := os.OpenFile(outPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
			if err != nil {
				return fmt.Errorf("failed to create trace file for block %d: %w", i, err)
			}
			outW = file
		}

		// Process the block using sequencer logic
		result, newStateRoot, err := processBlockWithSequencerLogic(logger, config, chCtx, replayMiner, block, outW, outDir)

		// Close the file immediately after processing the block
		if outDir != "" {
			if file, ok := outW.(*os.File); ok {
				file.Close()
			}
		}

		if err != nil {
			logger.Error("Failed to process block", "number", i, "error", err)
			return fmt.Errorf("failed to process block %d: %w", i, err)
		}

		totalBlocks++

		// Compare state roots
		expectedRoot := block.Root()
		if newStateRoot != expectedRoot {
			mismatchBlocks++
			logger.Error("State root mismatch",
				"block_number", i,
				"expected_root", expectedRoot,
				"computed_root", newStateRoot,
				"gas_used", result.GasUsed)
		} else {
			successBlocks++
			logger.Info("Block processed successfully",
				"block_number", i,
				"state_root", newStateRoot,
				"gas_used", result.GasUsed,
				"tx_count", len(block.Transactions()))
		}

		// Update current state to the new state for next block
		// Note: We need to create a new StateDB instance because the current one is already committed
		currentState, err = gstate.New(newStateRoot, stateDB)
		if err != nil {
			return fmt.Errorf("failed to create state for next block: %w", err)
		}

		// Update the remoteChainCtx for the next block processing
		chCtx.currentState = currentState // Update state for next block
		chCtx.hdr = block.Header()        // Update header to current block (will be parent for next block)

		// Update previous block hash for next iteration
		prevBlockHash = block.Hash()
	}

	// Print summary
	logger.Info("Replay completed",
		"total_blocks", totalBlocks,
		"success_blocks", successBlocks,
		"mismatch_blocks", mismatchBlocks,
		"success_rate", fmt.Sprintf("%.2f%%", float64(successBlocks)/float64(totalBlocks)*100))

	if mismatchBlocks > 0 {
		return fmt.Errorf("state root mismatches detected in %d out of %d blocks", mismatchBlocks, totalBlocks)
	}

	return nil
}

// =============================================================================
// Block Processing Logic (Core Replay Functionality)
// =============================================================================

// processBlockWithSequencerLogic processes a single block using sequencer logic and returns the new state root
func processBlockWithSequencerLogic(logger log.Logger, config *params.ChainConfig, chCtx *remoteChainCtx, replayMiner *ReplayMiner, block *types.Block,
	outW io.Writer, outDir string) (*core.ProcessResult, common.Hash, error) {

	header := block.Header()

	vmCfg := vm.Config{Tracer: nil}

	// Set up tracing only if output is requested
	if outW != nil && outW != io.Discard {
		vmCfg.Tracer = logger2.NewJSONLogger(&logger2.Config{
			EnableMemory:     false,
			DisableStack:     false,
			DisableStorage:   false,
			EnableReturnData: false,
			Limit:            0,
			Overrides:        nil,
		}, outW)
	}

	// Witness creation and prefetcher management is now handled in makeEnv method
	// to align with miner logic and avoid duplication

	params := extractGenerateParams(block)

	// Use miner's call chain: generateWork -> prepareWork -> makeEnv -> commitTransaction -> applyTransaction
	// Pass vmCfg to enable tracing
	result := replayMiner.generateWork(params, outDir != "", block, vmCfg)
	if result.err != nil {
		return nil, common.Hash{}, fmt.Errorf("failed to generate work: %w", result.err)
	}

	// Export witness data for debugging if output directory is specified (replay-specific logic)
	// This is now handled after generateWork to align with miner logic structure
	if outDir != "" && result.witness != nil {
		witnessDump := result.witness.ToExecutionWitness()
		out, err := json.MarshalIndent(witnessDump, "", "  ")
		if err != nil {
			logger.Error("failed to encode witness", "err", err)
		} else {
			witnessPath := fmt.Sprintf("%s/block_%d_witness.json", outDir, block.NumberU64())
			if err := os.WriteFile(witnessPath, out, 0644); err != nil {
				logger.Debug("Failed to write witness", "err", err, "path", witnessPath)
			} else {
				logger.Info("Witness data exported", "path", witnessPath)
			}
		}
	}

	// Commit the state changes and get the new state root
	newStateRoot, err := chCtx.currentState.Commit(uint64(block.NumberU64()), config.IsEIP158(header.Number), config.IsCancun(header.Number, header.Time))
	if err != nil {
		return nil, common.Hash{}, fmt.Errorf("failed to commit state: %w", err)
	}

	return &core.ProcessResult{
		Receipts: result.receipts,
		Requests: result.requests,
		Logs: func() []*types.Log {
			var allLogs []*types.Log
			for _, r := range result.receipts {
				allLogs = append(allLogs, r.Logs...)
			}
			return allLogs
		}(),
		GasUsed: result.block.GasUsed(),
	}, newStateRoot, nil
}

// =============================================================================
// ReplayMiner Implementation (Mimicking Miner Logic)
// =============================================================================

// NewReplayMiner creates a new replay miner instance
func NewReplayMiner(config *params.ChainConfig, chain *remoteChainCtx, logger log.Logger) *ReplayMiner {
	return &ReplayMiner{
		chainConfig: config,
		chain:       chain,
		logger:      logger,
	}
}

// extractGenerateParams extracts miner parameters from an existing block
// This is replay-specific logic that miner doesn't have
func extractGenerateParams(block *types.Block) *generateParams {
	return &generateParams{
		timestamp:     block.Time(),
		forceTime:     true, // Timestamp is fixed in replay mode
		parentHash:    block.ParentHash(),
		coinbase:      block.Coinbase(),
		random:        block.MixDigest(),
		withdrawals:   block.Withdrawals(),
		beaconRoot:    block.BeaconRoot(),
		noTxs:         true, // Transactions are forced-included in replay mode
		txs:           block.Transactions(),
		gasLimit:      func() *uint64 { limit := block.GasLimit(); return &limit }(),
		eip1559Params: nil,
		interrupt:     nil,
		isUpdate:      false,
		rpcCtx:        nil,
	}
}

// generateWork mimics miner's generateWork method
// DIFFERENCES FROM MINER:
// - Skips fillTransactions logic (transactions are already determined)
// - Skips interrupt checks (no interruption needed in replay)
// - Uses existing block for FinalizeAndAssemble
// - Receives vmCfg for tracing support
func (rm *ReplayMiner) generateWork(params *generateParams, witness bool, block *types.Block, vmCfg vm.Config) *newPayloadResult {
	work, err := rm.prepareWork(params, witness, block, vmCfg)
	if err != nil {
		return &newPayloadResult{err: err}
	}

	if work.gasPool == nil {
		gasLimit := work.header.GasLimit
		work.gasPool = new(core.GasPool).AddGas(gasLimit)
	}

	misc.EnsureCreate2Deployer(rm.chainConfig, work.header.Time, work.state)

	// Process forced transactions (from block)
	for i, tx := range params.txs {
		rm.logger.Info("Processing tx", "i", i, "hash", tx.Hash().Hex())
		from, _ := types.Sender(work.signer, tx)
		work.state.SetTxContext(tx.Hash(), work.tcount)
		err = rm.commitTransaction(work, tx)
		if err != nil {
			return &newPayloadResult{err: fmt.Errorf("failed to force-include tx: %s type: %d sender: %s nonce: %d, err: %w", tx.Hash(), tx.Type(), from, tx.Nonce(), err)}
		}
	}

	// SKIPPED: fillTransactions logic (not needed in replay mode)
	// SKIPPED: interrupt checks (no interruption needed in replay mode)

	body := types.Body{Transactions: work.txs, Withdrawals: params.withdrawals}
	allLogs := make([]*types.Log, 0)
	for _, r := range work.receipts {
		allLogs = append(allLogs, r.Logs...)
	}

	isIsthmus := rm.chainConfig.IsIsthmus(work.header.Time)

	// Collect consensus-layer requests if Prague is enabled
	var requests [][]byte
	if rm.chainConfig.IsPrague(work.header.Number, work.header.Time) && !isIsthmus {
		requests = [][]byte{}
		// EIP-6110 deposits
		if err := core.ParseDepositLogs(&requests, allLogs, rm.chainConfig); err != nil {
			return &newPayloadResult{err: err}
		}
		// EIP-7002
		if err := core.ProcessWithdrawalQueue(&requests, work.evm); err != nil {
			return &newPayloadResult{err: err}
		}
		// EIP-7251 consolidations
		if err := core.ProcessConsolidationQueue(&requests, work.evm); err != nil {
			return &newPayloadResult{err: err}
		}
	}

	if isIsthmus {
		requests = [][]byte{}
	}

	if requests != nil {
		reqHash := types.CalcRequestsHash(requests)
		work.header.RequestsHash = &reqHash
	}

	// Use FinalizeAndAssemble to match miner logic exactly
	newBlock, err := rm.chain.Engine().FinalizeAndAssemble(rm.chain, work.header, work.state, &body, work.receipts)
	if err != nil {
		return &newPayloadResult{err: err}
	}

	return &newPayloadResult{
		block:    newBlock,
		fees:     totalFees(newBlock, work.receipts),
		sidecars: work.sidecars,
		stateDB:  work.state,
		receipts: work.receipts,
		requests: requests,
		witness:  work.witness,
	}
}

// prepareWork mimics miner's prepareWork method
// DIFFERENCES FROM MINER:
// - Uses external parent block instead of fetching from chain
// - Uses existing block's Extra and BaseFee instead of computing them
// - Simplified gas limit handling
// - Receives vmCfg for tracing support
func (rm *ReplayMiner) prepareWork(genParams *generateParams, witness bool, block *types.Block, vmCfg vm.Config) (*environment, error) {
	// In replay mode, we don't need to check parent block since we already have the complete block
	parent := rm.chain.CurrentHeader()

	// Timestamp validation
	timestamp := genParams.timestamp
	if parent.Time >= timestamp {
		if genParams.forceTime {
			return nil, fmt.Errorf("invalid timestamp, parent %d given %d", parent.Time, timestamp)
		}
		timestamp = parent.Time + 1
	}

	// Construct block header
	header := &types.Header{
		ParentHash: parent.Hash(),
		Number:     new(big.Int).Add(parent.Number, common.Big1),
		GasLimit:   parent.GasLimit, // Use parent's gas limit instead of computing
		Time:       timestamp,
		Coinbase:   genParams.coinbase,
	}

	// Use existing block's Extra data instead of computing
	header.Extra = block.Extra()

	if genParams.random != (common.Hash{}) {
		header.MixDigest = genParams.random
	}

	// Set EIP-1559 related fields
	if rm.chainConfig.IsLondon(header.Number) {
		// Use existing block's BaseFee instead of computing
		header.BaseFee = block.BaseFee()
	}

	// Run consensus preparation
	if err := rm.chain.Engine().Prepare(rm.chain, header); err != nil {
		rm.logger.Error("Failed to prepare header for sealing", "err", err)
		return nil, err
	}

	// Apply EIP-4844, EIP-4788
	if rm.chainConfig.IsCancun(header.Number, header.Time) {
		var excessBlobGas uint64
		if rm.chainConfig.IsCancun(parent.Number, parent.Time) {
			excessBlobGas = eip4844.CalcExcessBlobGas(rm.chainConfig, parent, timestamp)
		}
		header.BlobGasUsed = new(uint64)
		header.ExcessBlobGas = &excessBlobGas
		header.ParentBeaconRoot = genParams.beaconRoot
	}

	// Create environment
	env, err := rm.makeEnv(header, genParams.coinbase, witness, genParams.rpcCtx, vmCfg)
	if err != nil {
		rm.logger.Error("Failed to create sealing context", "err", err)
		return nil, err
	}

	env.noTxs = genParams.noTxs

	// Process beacon root
	if header.ParentBeaconRoot != nil {
		core.ProcessBeaconBlockRoot(*header.ParentBeaconRoot, env.evm)
	}

	// Process Prague related logic
	if rm.chainConfig.IsPrague(header.Number, header.Time) {
		core.ProcessParentBlockHash(header.ParentHash, env.evm)
	}

	return env, nil
}

// makeEnv mimics miner's makeEnv method
// DIFFERENCES FROM MINER:
// - Uses external state instead of fetching from chain
// - Simplified state access logic
// - Handles witness export for replay debugging
// - Receives vmCfg for tracing support
func (rm *ReplayMiner) makeEnv(header *types.Header, coinbase common.Address, witness bool, rpcCtx context.Context, vmCfg vm.Config) (*environment, error) {
	// In replay mode, we use externally provided state
	state := rm.chain.currentState

	if witness {
		bundle, err := stateless.NewWitness(header, rm.chain)
		if err != nil {
			return nil, err
		}
		state.StartPrefetcher("replay", bundle)

		// Export witness data for debugging (replay-specific logic)
		// This is moved from processBlockWithSequencerLogic to align with miner logic
		if rm.chain.logger != nil {
			rm.chain.logger.Info("Witness created and prefetcher started for replay debugging")
		}
	}

	return &environment{
		signer:   types.MakeSigner(rm.chainConfig, header.Number, header.Time),
		state:    state,
		coinbase: coinbase,
		header:   header,
		witness:  state.Witness(),
		evm:      vm.NewEVM(core.NewEVMBlockContext(header, rm.chain, &coinbase, rm.chainConfig, state), state, rm.chainConfig, vmCfg),
		rpcCtx:   rpcCtx,
	}, nil
}

// commitTransaction mimics miner's commitTransaction method
// DIFFERENCES FROM MINER:
// - Skips interop transaction checks (not needed in replay mode)
// - Simplified conditional transaction handling
func (rm *ReplayMiner) commitTransaction(env *environment, tx *types.Transaction) error {
	// Check conditional transaction if present
	if conditional := tx.Conditional(); conditional != nil {
		// Check header conditional
		if err := env.header.CheckTransactionConditional(conditional); err != nil {
			return fmt.Errorf("failed header check: %s: %w", err, errTxConditionalInvalid)
		}
		// Check state conditional
		if err := env.state.CheckTransactionConditional(conditional); err != nil {
			return fmt.Errorf("failed state check: %s: %w", err, errTxConditionalInvalid)
		}
	}

	receipt, err := rm.applyTransaction(env, tx)
	if err != nil {
		return err
	}
	env.txs = append(env.txs, tx)
	env.receipts = append(env.receipts, receipt)
	env.tcount++
	return nil
}

// applyTransaction mimics miner's applyTransaction method
// DIFFERENCES FROM MINER:
// - None (completely identical logic)
func (rm *ReplayMiner) applyTransaction(env *environment, tx *types.Transaction) (*types.Receipt, error) {
	var (
		snap = env.state.Snapshot()
		gp   = env.gasPool.Gas()
	)
	receipt, err := core.ApplyTransaction(env.evm, env.gasPool, env.state, env.header, tx, &env.header.GasUsed)
	if err != nil {
		env.state.RevertToSnapshot(snap)
		env.gasPool.SetGas(gp)
	}
	return receipt, err
}

// =============================================================================
// Utility Functions
// =============================================================================

// totalFees computes total consumed miner fees in Wei. Block transactions and receipts have to have the same order.
func totalFees(block *types.Block, receipts []*types.Receipt) *big.Int {
	feesWei := new(big.Int)
	for i, tx := range block.Transactions() {
		minerFee, _ := tx.EffectiveGasTip(block.BaseFee())
		feesWei.Add(feesWei, new(big.Int).Mul(new(big.Int).SetUint64(receipts[i].GasUsed), minerFee))
		// TODO (MariusVanDerWijden) add blob fees
	}
	return feesWei
}

// =============================================================================
// Chain Context Implementation (Implementing Required Interfaces)
// =============================================================================

var _ core.ChainContext = (*remoteChainCtx)(nil)
var _ consensus.ChainHeaderReader = (*remoteChainCtx)(nil)

// Config is part of consensus.ChainHeaderReader
func (r *remoteChainCtx) Config() *params.ChainConfig {
	return r.cfg
}

// CurrentHeader is part of consensus.ChainHeaderReader
func (r remoteChainCtx) CurrentHeader() *types.Header {
	return r.hdr
}

// GetHeaderByNumber is part of consensus.ChainHeaderReader
func (r remoteChainCtx) GetHeaderByNumber(u uint64) *types.Header {
	if r.hdr.Number.Uint64() == u {
		return r.hdr
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()
	hdr, err := retry.Do[*types.Header](ctx, 10, retry.Exponential(), func() (*types.Header, error) {
		r.logger.Info("fetching block header", "num", u)
		return r.cl.HeaderByNumber(ctx, new(big.Int).SetUint64(u))
	})
	if err != nil {
		r.logger.Error("failed to get block header", "err", err, "num", u)
		return nil
	}
	if hdr == nil {
		r.logger.Warn("header not found", "num", u)
	}
	return hdr
}

// GetHeaderByHash is part of consensus.ChainHeaderReader
func (r remoteChainCtx) GetHeaderByHash(hash common.Hash) *types.Header {
	if r.hdr.Hash() == hash {
		return r.hdr
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()
	hdr, err := retry.Do[*types.Header](ctx, 10, retry.Exponential(), func() (*types.Header, error) {
		r.logger.Info("fetching block header", "hash", hash)
		return r.cl.HeaderByHash(ctx, hash)
	})
	if err != nil {
		r.logger.Error("failed to get block header", "err", err, "hash", hash)
		return nil
	}
	if hdr == nil {
		r.logger.Warn("header not found", "hash", hash)
	}
	return hdr
}

// GetTd is part of consensus.ChainHeaderReader
func (r remoteChainCtx) GetTd(hash common.Hash, number uint64) *big.Int {
	return big.NewInt(1)
}

// Engine is part of core.ChainContext
func (r remoteChainCtx) Engine() consensus.Engine {
	return r.consensusEng
}

// GetHeader is part of both consensus.ChainHeaderReader and core.ChainContext
func (r remoteChainCtx) GetHeader(hash common.Hash, u uint64) *types.Header {
	if r.hdr.Hash() == hash {
		return r.hdr
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()
	hdr, err := retry.Do[*types.Header](ctx, 10, retry.Exponential(), func() (*types.Header, error) {
		r.logger.Info("fetching block header", "hash", hash, "num", u)
		return r.cl.HeaderByNumber(ctx, new(big.Int).SetUint64(u))
	})
	if err != nil {
		r.logger.Error("failed to get block header", "err", err, "hash", hash, "num", u)
		return nil
	}
	if hdr == nil {
		r.logger.Warn("header not found", "hash", hash, "num", u)
	}
	if got := hdr.Hash(); got != hash {
		r.logger.Error("fetched incompatible header", "expectedHash", hash, "fetchedHash", got, "num", u)
	}
	return hdr
}
