version: '3.8'

networks:
  xlayer-network:
    name: xlayer-rpc-network

services:
  op-geth:
    image: "${OP_GETH_IMAGE_TAG}"
    container_name: xlayer-op-geth
    entrypoint: geth
    ports:
      - "8124:8545"   # HTTP RPC
      - "30304:30303" # P2P TCP
      - "30304:30303/udp" # P2P UDP
    volumes:
      - ./data/op-geth:/datadir
      - ./config/jwt.txt:/jwt.txt
      - ./config/op-geth-config.toml:/config.toml
    command:
      - --verbosity=3
      - --datadir=/datadir
      - --config=/config.toml
      - --authrpc.jwtsecret=/jwt.txt
      - --gcmode=archive
      - --rollup.enabletxpooladmission

  op-node:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: xlayer-op-node
    ports:
      - "9555:9545"
    volumes:
      - ./data/op-node:/data
      - ./config/rollup.json:/rollup.json
      - ./config/jwt.txt:/jwt.txt
      - ./config/genesis.json:/l1-genesis.json
    command:
      - /app/op-node/bin/op-node
      - --log.level=info
      - --l2=http://op-geth:8552
      - --l2.jwt-secret=/jwt.txt
      - --sequencer.enabled=false
      - --verifier.l1-confs=1
      - --rollup.config=/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --p2p.listen.tcp=9223
      - --p2p.listen.udp=9223
      - --p2p.priv.raw=604557d042fbea9ed42f46c0c95c346a932b6a5ef0c0dd07a00dbf95801a2510
      - --p2p.peerstore.path=/data/p2p/opnode_peerstore_db
      - --p2p.discovery.path=/data/p2p/opnode_discovery_db
      - --p2p.bootnodes=enr:-J24QMKrCjD9yO_etOJmxFNAJdJayoNLzx2SKRD4amiEtYHSAgaQIheHntQ8hQLby7ejqwPQzMuT6nys9MBfU0yeVZaGAZnq6jJvgmlkgnY0gmlwhAjStTKHb3BzdGFja4OgDwCJc2VjcDI1NmsxoQPqrp_i_HWK3WX-TP1CkY6JjharIylNuI8NzbyrJ3PnW4N0Y3CCJAeDdWRwgiQH
      - --p2p.no-discovery
      - --rpc.enable-admin=true
      - --l1=${L1_RPC_URL}
      - --l1.beacon=${L1_BEACON_URL}
      - --rollup.l1-chain-config=/l1-genesis.json
      - --safedb.path=/data/safedb
    depends_on:
      - op-geth
