--
-- Copyright 2024 Apollo Authors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- ${gists.autoGeneratedDeclaration}
-- ${gists.h2Function}
-- ${gists.setupDatabase}

-- Dump of table app
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `App`;

CREATE TABLE `App` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `Name` varchar(500) NOT NULL DEFAULT 'default' COMMENT 'Application name',
  `OrgId` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Organization ID',
  `OrgName` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Organization name',
  `OwnerName` varchar(500) NOT NULL DEFAULT 'default' COMMENT 'Owner name',
  `OwnerEmail` varchar(500) NOT NULL DEFAULT 'default' COMMENT 'Owner email',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_AppId_DeletedAt` (`AppId`,`DeletedAt`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_Name` (`Name`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application table';



-- Dump of table appnamespace
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `AppNamespace`;

CREATE TABLE `AppNamespace` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT 'Namespace name, needs to be globally unique',
  `AppId` varchar(64) NOT NULL DEFAULT '' COMMENT 'Application ID',
  `Format` varchar(32) NOT NULL DEFAULT 'properties' COMMENT 'Namespace format type',
  `IsPublic` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether namespace is public',
  `Comment` varchar(64) NOT NULL DEFAULT '' COMMENT 'Comment',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_AppId_Name_DeletedAt` (`AppId`,`Name`,`DeletedAt`),
  KEY `Name_AppId` (`Name`,`AppId`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application namespace definition';



-- Dump of table audit
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Audit`;

CREATE TABLE `Audit` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `EntityName` varchar(50) NOT NULL DEFAULT 'default' COMMENT 'Table name',
  `EntityId` int(10) unsigned DEFAULT NULL COMMENT 'Record ID',
  `OpName` varchar(50) NOT NULL DEFAULT 'default' COMMENT 'Operation type',
  `Comment` varchar(500) DEFAULT NULL COMMENT 'Comment',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Audit log table';



-- Dump of table cluster
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Cluster`;

CREATE TABLE `Cluster` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT 'Cluster name',
  `AppId` varchar(64) NOT NULL DEFAULT '' COMMENT 'Application ID',
  `ParentClusterId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Parent cluster',
  `Comment` varchar(64) DEFAULT NULL COMMENT 'Comment',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_AppId_Name_DeletedAt` (`AppId`,`Name`,`DeletedAt`),
  KEY `IX_ParentClusterId` (`ParentClusterId`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Cluster';



-- Dump of table commit
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Commit`;

CREATE TABLE `Commit` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `ChangeSets` longtext NOT NULL COMMENT 'Change sets',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `NamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Namespace name',
  `Comment` varchar(500) DEFAULT NULL COMMENT 'Comment',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `AppId` (`AppId`),
  KEY `ClusterName` (`ClusterName`),
  KEY `NamespaceName` (`NamespaceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Commit history table';

-- Dump of table grayreleaserule
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `GrayReleaseRule`;

CREATE TABLE `GrayReleaseRule` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `NamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Namespace name',
  `BranchName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Branch name',
  `Rules` varchar(16000) DEFAULT '[]' COMMENT 'Gray release rules',
  `ReleaseId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Gray release ID',
  `BranchStatus` tinyint(2) DEFAULT '1' COMMENT 'Gray branch status: 0:delete branch, 1:active rule, 2:full release',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_Namespace` (`AppId`,`ClusterName`,`NamespaceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Gray release rule table';


-- Dump of table instance
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Instance`;

CREATE TABLE `Instance` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `DataCenter` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Data center name',
  `Ip` varchar(32) NOT NULL DEFAULT '' COMMENT 'Instance IP',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IX_UNIQUE_KEY` (`AppId`,`ClusterName`,`Ip`,`DataCenter`),
  KEY `IX_IP` (`Ip`),
  KEY `IX_DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application instances using configuration';



-- Dump of table instanceconfig
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `InstanceConfig`;

CREATE TABLE `InstanceConfig` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `InstanceId` int(11) unsigned DEFAULT NULL COMMENT 'Instance ID',
  `ConfigAppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Config application ID',
  `ConfigClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Config cluster name',
  `ConfigNamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Config namespace name',
  `ReleaseKey` varchar(64) NOT NULL DEFAULT '' COMMENT 'Release key',
  `ReleaseDeliveryTime` timestamp NULL DEFAULT NULL COMMENT 'Configuration delivery time',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IX_UNIQUE_KEY` (`InstanceId`,`ConfigAppId`,`ConfigNamespaceName`),
  KEY `IX_ReleaseKey` (`ReleaseKey`),
  KEY `IX_DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_Valid_Namespace` (`ConfigAppId`,`ConfigClusterName`,`ConfigNamespaceName`,`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Application instance configuration information';



-- Dump of table item
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Item`;

CREATE TABLE `Item` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `NamespaceId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Cluster namespace ID',
  `Key` varchar(128) NOT NULL DEFAULT 'default' COMMENT 'Configuration item key',
  `Type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Configuration item type: 0:String, 1:Number, 2:Boolean, 3:JSON',
  `Value` longtext NOT NULL COMMENT 'Configuration item value',
  `Comment` varchar(1024) DEFAULT '' COMMENT 'Comment',
  `LineNum` int(10) unsigned DEFAULT '0' COMMENT 'Line number',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `IX_GroupId` (`NamespaceId`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Configuration item';



-- Dump of table namespace
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Namespace`;

CREATE TABLE `Namespace` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `NamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Namespace name',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_AppId_ClusterName_NamespaceName_DeletedAt` (`AppId`,`ClusterName`,`NamespaceName`,`DeletedAt`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_NamespaceName` (`NamespaceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Namespace';



-- Dump of table namespacelock
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `NamespaceLock`;

CREATE TABLE `NamespaceLock` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `NamespaceId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Cluster namespace ID',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  `IsDeleted` bit(1) DEFAULT b'0' COMMENT 'Soft delete',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_NamespaceId_DeletedAt` (`NamespaceId`,`DeletedAt`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Namespace edit lock';



-- Dump of table release
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `Release`;

CREATE TABLE `Release` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `ReleaseKey` varchar(64) NOT NULL DEFAULT '' COMMENT 'Release key',
  `Name` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Release name',
  `Comment` varchar(256) DEFAULT NULL COMMENT 'Release description',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `NamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Namespace name',
  `Configurations` longtext NOT NULL COMMENT 'Release configurations',
  `IsAbandoned` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether abandoned',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_ReleaseKey_DeletedAt` (`ReleaseKey`,`DeletedAt`),
  KEY `AppId_ClusterName_GroupName` (`AppId`,`ClusterName`,`NamespaceName`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Release';


-- Dump of table releasehistory
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `ReleaseHistory`;

CREATE TABLE `ReleaseHistory` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `ClusterName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Cluster name',
  `NamespaceName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Namespace name',
  `BranchName` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Release branch name',
  `ReleaseId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Associated release ID',
  `PreviousReleaseId` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Previous release ID',
  `Operation` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Release type: 0:normal, 1:rollback, 2:gray, 3:gray rule update, 4:gray merge to master, 5:master auto gray, 6:master rollback auto gray, 7:abandon gray',
  `OperationContext` longtext NOT NULL COMMENT 'Release context information',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `IX_Namespace` (`AppId`,`ClusterName`,`NamespaceName`,`BranchName`),
  KEY `IX_ReleaseId` (`ReleaseId`),
  KEY `IX_DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_PreviousReleaseId` (`PreviousReleaseId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Release history';


-- Dump of table releasemessage
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `ReleaseMessage`;

CREATE TABLE `ReleaseMessage` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `Message` varchar(1024) NOT NULL DEFAULT '' COMMENT 'Release message content',
  `DataChange_LastTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_Message` (`Message`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Release message';



-- Dump of table serverconfig
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `ServerConfig`;

CREATE TABLE `ServerConfig` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `Key` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Configuration item key',
  `Cluster` varchar(32) NOT NULL DEFAULT 'default' COMMENT 'Configuration cluster, default for non-specific cluster',
  `Value` varchar(2048) NOT NULL DEFAULT 'default' COMMENT 'Configuration item value',
  `Comment` varchar(1024) DEFAULT '' COMMENT 'Comment',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_Key_Cluster_DeletedAt` (`Key`,`Cluster`,`DeletedAt`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Configuration service self configuration';

-- Dump of table accesskey
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `AccessKey`;

CREATE TABLE `AccessKey` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto increment primary key',
  `AppId` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Application ID',
  `Secret` varchar(128) NOT NULL DEFAULT '' COMMENT 'Secret',
  `Mode` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Key mode: 0:filter, 1:observer',
  `IsEnabled` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: enabled, 0: disabled',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) NOT NULL DEFAULT 'default' COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_AppId_Secret_DeletedAt` (`AppId`,`Secret`,`DeletedAt`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Access key';


-- Dump of table serviceregistry
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `ServiceRegistry`;

CREATE TABLE `ServiceRegistry` (
  `Id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto increment ID',
  `ServiceName` VARCHAR(64) NOT NULL COMMENT 'Service name',
  `Uri` VARCHAR(64) NOT NULL COMMENT 'Service address',
  `Cluster` VARCHAR(64) NOT NULL COMMENT 'Cluster, can be used to identify apollo.cluster or network partition',
  `Metadata` VARCHAR(1024) NOT NULL DEFAULT '{}' COMMENT 'Metadata, key-value JSON object for future extension without table structure changes',
  `DataChange_CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `IX_UNIQUE_KEY` (`ServiceName`, `Uri`),
  INDEX `IX_DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Service registry';

-- Dump of table AuditLog
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `AuditLog`;

CREATE TABLE `AuditLog` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `TraceId` varchar(32) NOT NULL DEFAULT '' COMMENT 'Global unique trace ID',
  `SpanId` varchar(32) NOT NULL DEFAULT '' COMMENT 'Span ID',
  `ParentSpanId` varchar(32) DEFAULT NULL COMMENT 'Parent span ID',
  `FollowsFromSpanId` varchar(32) DEFAULT NULL COMMENT 'Previous sibling span ID',
  `Operator` varchar(64) NOT NULL DEFAULT 'anonymous' COMMENT 'Operator',
  `OpType` varchar(50) NOT NULL DEFAULT 'default' COMMENT 'Operation type',
  `OpName` varchar(150) NOT NULL DEFAULT 'default' COMMENT 'Operation name',
  `Description` varchar(200) DEFAULT NULL COMMENT 'Description',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) DEFAULT NULL COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `IX_TraceId` (`TraceId`),
  KEY `IX_OpName` (`OpName`),
  KEY `IX_DataChange_CreatedTime` (`DataChange_CreatedTime`),
  KEY `IX_Operator` (`Operator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Audit log table';

-- Dump of table AuditLogDataInfluence
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `AuditLogDataInfluence`;

CREATE TABLE `AuditLogDataInfluence` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `SpanId` char(32) NOT NULL DEFAULT '' COMMENT 'Span ID',
  `InfluenceEntityId` varchar(50) NOT NULL DEFAULT '0' COMMENT 'Record ID',
  `InfluenceEntityName` varchar(50) NOT NULL DEFAULT 'default' COMMENT 'Table name',
  `FieldName` varchar(50) DEFAULT NULL COMMENT 'Field name',
  `FieldOldValue` varchar(500) DEFAULT NULL COMMENT 'Field old value',
  `FieldNewValue` varchar(500) DEFAULT NULL COMMENT 'Field new value',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  `DeletedAt` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'Delete timestamp based on milliseconds',
  `DataChange_CreatedBy` varchar(64) DEFAULT NULL COMMENT 'Creator email prefix',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `DataChange_LastModifiedBy` varchar(64) DEFAULT '' COMMENT 'Last modified by email prefix',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification time',
  PRIMARY KEY (`Id`),
  KEY `IX_SpanId` (`SpanId`),
  KEY `IX_DataChange_CreatedTime` (`DataChange_CreatedTime`),
  KEY `IX_EntityId` (`InfluenceEntityId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Audit log data change table';

-- Config
-- ------------------------------------------------------------
INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('eureka.service.url', 'default', 'http://apollo-configservice:8085/eureka/', 'Eureka service URL, multiple services separated by commas'),
    ('namespace.lock.switch', 'default', 'false', 'One release can only be modified by one person switch'),
    ('item.key.length.limit', 'default', '128', 'Item key maximum length limit'),
    ('item.value.length.limit', 'default', '20000', 'Item value maximum length limit'),
    ('config-service.cache.enabled', 'default', 'false', 'Whether ConfigService enables cache, can improve performance but increases memory consumption!');

-- ${gists.autoGeneratedDeclaration}

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
